name: Repo Info with context

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v3

      - name: show branch info and GitHub context
        run: |
          echo Info follows on ${{ github.repository }}
          echo Default branch is "main"
          echo Size of repository is `du -hs ${{ github.workspace }}`
          
      - name: Dump job context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
                
   # add your jobs here     
